### PR TITLE
add localization for filepond

### PR DESCRIPTION
**Pull request by uluumbch**
Add a localization options for use in filepond views #6 

I use all translation from original filepond [locales repo](https://github.com/pqina/filepond/tree/master/locale) and then convert it to PHP syntax.

Some of the language code may not suit with the laravel language naming convention, I am referring to [Laravel Lang](https://laravel-lang.com/available-locales-list.html) website to change the localization folder name because it is different from filepond's locale name. Please give me feedback if there might be any mistake in the folder name

### CODE REVIEW

**Comment by StanBarrows** [comment]
@uluumbch 

Cool! Can you also give an example on how to change the locale with your implementation? Maybe in the readme.md?

Cheers
Sebastian

**Comment by uluumbch** [comment]
> @uluumbch
> 
> Cool! Can you also give an example on how to change the locale with your implementation? Maybe in the readme.md?
> 
> Cheers Sebastian

Sounds good, I've added some changes to the readme file to provide usage instructions.

**Comment by riasvdv** [comment]
Thanks!

**Comment by RoccoHoward** [comment]
@uluumbch  This beaks overriding the placeholder option `labelIdle`

**Pull request merged**
